import {
  AiOutlineDatabase,
  AiOutlineEdit,
  AiOutlineLayout,
} from "react-icons/ai";
import { HiOutlineAcademicCap, HiOutlineChartSquareBar } from "react-icons/hi";
import {
  RiBarChart2Line,
  RiCustomerService2Line,
  RiDashboardLine,
  RiEqualizerLine,
  RiFileUploadLine,
  RiShieldUserLine,
  RiTodoLine,
} from "react-icons/ri";
import {
  BiBookReader,
  BiCarousel,
  BiCartAlt,
  BiData,
  BiDollar,
  BiErrorCircle,
  BiRss,
  BiTask,
} from "react-icons/bi";
import {
  MdDevicesOther,
  MdInvertColors,
  MdOutlineAnalytics,
  MdOutlineContactPhone,
  MdOutlineContactSupport,
  MdOutlineDns,
  MdOutlineManageAccounts,
  MdTimeline,
} from "react-icons/md";
import { VscFeedback } from "react-icons/vsc";
import {
  BsBriefcase,
  BsCart4,
  BsChatDots,
  BsCurrencyBitcoin,
  BsQuestionDiamond,
  BsTable,
} from "react-icons/bs";
import { GiCloverSpiked } from "react-icons/gi";
import { FaRegCalendarAlt, FaRegHospital, FaRegImages } from "react-icons/fa";
import { CgAttachment, CgFeed, CgUserList } from "react-icons/cg";
import { TiMap } from "react-icons/ti";
import { FiMail, FiMap, FiUsers } from "react-icons/fi";
import { IoMdNotificationsOutline } from "react-icons/io";
import { DiHtml5Multimedia } from "react-icons/di";
import { RoutePermittedRole } from "@crema/constants/AppEnums";
import { GrUserAdmin } from "react-icons/gr";
import { TbFileInvoice } from "react-icons/tb";

const routesConfig = [
  {
    id: "dashboards",
    title: "Application",
    messageId: "sidebar.application",
    type: "group",
    children: [
      {
        id: "crypto",
        title: "Crypto",
        messageId: "sidebar.app.dashboard.crypto",
        icon: <BsCurrencyBitcoin />,
        url: "/dashboards/crypto",
      },
      {
        id: "crm",
        title: "CRM",
        messageId: "sidebar.app.dashboard.crm",
        icon: <RiCustomerService2Line />,
        url: "/dashboards/crm",
      },
      {
        id: "analytics",
        title: "Analytics",
        messageId: "sidebar.app.dashboard.analytics",
        icon: <MdOutlineAnalytics />,
        url: "/dashboards/analytics",
      },
      {
        id: "health-care",
        title: "Health Care",
        permittedRole: RoutePermittedRole.User,
        messageId: "sidebar.healthCare",
        icon: <FaRegHospital />,
        url: "/dashboards/health-care",
      },
      {
        id: "e-commerce",
        title: "E-Commerce",
        messageId: "sidebar.app.dashboard.eCommerce",
        icon: <BsCart4 />,
        url: "/dashboards/e-commerce",
      },
      {
        id: "academy",
        title: "Academy",
        messageId: "sidebar.app.dashboard.academy",
        icon: <HiOutlineAcademicCap />,
        url: "/dashboards/academy",
      },
      {
        id: "metrics",
        title: "Metrics",
        messageId: "sidebar.app.metrics",
        icon: <HiOutlineChartSquareBar />,
        url: "/dashboards/metrics",
      },
      {
        id: "widgets",
        title: "Widgets",
        messageId: "sidebar.app.widgets",
        icon: <RiDashboardLine />,
        url: "/dashboards/widgets",
      },
    ],
  },
  {
    id: "apps",
    title: "Apps",
    messageId: "sidebar.apps",
    type: "group",
    children: [
      {
        id: "mail",
        title: "Mail",
        messageId: "sidebar.apps.mail",
        count: 4,
        icon: <FiMail />,
        url: "/apps/mail",
      },
      {
        id: "calender",
        title: "Calender",
        messageId: "sidebar.apps.calender",
        icon: <BiTask />,
        url: "/apps/calender",
      },
      {
        id: "todo",
        title: "ToDo",
        messageId: "sidebar.apps.todo",
        count: 6,
        icon: <RiTodoLine />,
        color: "#48bb78",
        url: "/apps/todo",
      },
      {
        id: "contact",
        title: "Contact",
        messageId: "sidebar.apps.contact",
        icon: <MdOutlineContactPhone />,
        url: "/apps/contact",
      },
      {
        id: "chat",
        title: "Chat",
        icon: <BsChatDots />,
        messageId: "sidebar.apps.chat",
        url: "/apps/chat",
      },
      {
        id: "scrum-board",
        title: "Scrum Board",
        messageId: "sidebar.apps.scrumboard",
        icon: <MdOutlineDns />,
        url: "/apps/scrum-board",
      },
      {
        id: "wall",
        title: "Wall",
        messageId: "sidebar.apps.wall",
        icon: <CgFeed />,
        url: "/apps/wall",
      },
      {
        id: "ecommerce",
        title: "Ecommerce",
        messageId: "sidebar.ecommerce",
        icon: <BiCartAlt />,
        type: "collapse",
        children: [
          {
            id: "products",
            title: "Products",
            messageId: "sidebar.ecommerce.products",
            url: "/apps/ecommerce/products",
          },
          {
            id: "product_detail",
            title: "Product Detail",
            messageId: "sidebar.ecommerce.productDetail",
            url: "/apps/ecommerce/product_detail",
          },
          {
            id: "orders",
            title: "Orders",
            messageId: "sidebar.ecommerce.orders",
            url: "/apps/ecommerce/orders",
          },
          {
            id: "cart",
            title: "Cart",
            messageId: "sidebar.ecommerce.cart",
            url: "/apps/ecommerce/cart",
          },
          {
            id: "checkout",
            title: "Checkout",
            messageId: "sidebar.ecommerce.checkout",
            url: "/apps/ecommerce/checkout",
          },
          {
            id: "confirmation",
            title: "Confirmation",
            messageId: "sidebar.ecommerce.confirmation",
            url: "/apps/ecommerce/confirmation",
          },
          {
            id: "invoice-1",
            title: "Invoice 1",
            messageId: "sidebar.ecommerce.invoice1",
            url: "/apps/ecommerce/invoice-1",
          },
          {
            id: "invoice-2",
            title: "Invoice 2",
            messageId: "sidebar.ecommerce.invoice2",
            url: "/apps/ecommerce/invoice-2",
          },
        ],
      },
      {
        id: "ecommerce-admin",
        title: "Ecommerce Admin",
        messageId: "sidebar.ecommerceAdmin",
        type: "collapse",
        icon: <GrUserAdmin />,
        children: [
          {
            id: "product-listing",
            title: "Product Listing",
            messageId: "sidebar.ecommerceAdmin.productListing",
            url: "/apps/ecommerce-admin/product-listing",
          },
          {
            id: "add-products",
            title: "Add Products",
            messageId: "sidebar.ecommerceAdmin.addProducts",
            url: "/apps/ecommerce-admin/add-products",
          },
          {
            id: "customers",
            title: "Customers",
            messageId: "sidebar.ecommerce.customers",
            url: "/apps/ecommerce-admin/customers",
          },
        ],
      },
      {
        id: "invoice",
        title: "Invoice",
        messageId: "sidebar.invoice",
        type: "collapse",
        icon: <TbFileInvoice />,
        children: [
          {
            id: "add",
            title: "Add Invoices",
            messageId: "sidebar.invoice.addInvoice",
            url: "/invoice/add",
          },
          {
            id: "invoices",
            title: "Invoices",
            messageId: "sidebar.invoice.home",
            url: "/invoice/invoices",
          },
          {
            id: "clients",
            title: "Clients",
            messageId: "sidebar.invoice.clients",
            url: "/invoice/clients",
          },
          {
            id: "settings",
            title: "Settings",
            messageId: "sidebar.invoice.settings",
            url: "/invoice/settings",
          },
        ],
      },
      {
        id: "blog",
        title: "Blog",
        messageId: "sidebar.pages.extraPages.blog",
        type: "collapse",
        icon: <BiRss />,
        children: [
          {
            id: "blog",
            title: "Blog List",
            messageId: "sidebar.pages.extraPages.blogList",
            url: "/extra-pages/blog",
          },
          {
            id: "blog-details",
            title: "Blog Detail",
            messageId: "sidebar.pages.extraPages.blogDetail",
            url: "/extra-pages/blog-details",
          },
          {
            id: "create-blog",
            title: "Create Blog",
            messageId: "sidebar.pages.extraPages.blogCreate",
            url: "/extra-pages/create-blog",
          },
        ],
      },
    ],
  },
  {
    id: "third-party",
    title: "Libs",
    messageId: "sidebar.libs",
    type: "group",
    children: [
      {
        id: "google-map",
        title: "Google Map",
        messageId: "sidebar.googleMap",
        icon: <FiMap />,
        url: "/third-party/google-map",
      },
      {
        id: "recharts",
        title: "Recharts",
        messageId: "sidebar.recharts",
        icon: <RiBarChart2Line />,
        url: "recharts",
        type: "collapse",
        children: [
          {
            id: "area",
            title: "Area Chart",
            messageId: "sidebar.recharts.areaChart",
            url: "/third-party/recharts/area",
          },
          {
            id: "bar",
            title: "Bar Chart",
            messageId: "sidebar.recharts.barChart",
            url: "/third-party/recharts/bar",
          },
          {
            id: "composed",
            title: "Composed Chart",
            messageId: "sidebar.recharts.composedChart",
            url: "/third-party/recharts/composed",
          },
          {
            id: "line",
            title: "Line Chart",
            messageId: "sidebar.recharts.lineChart",
            url: "/third-party/recharts/line",
          },
          {
            id: "pie",
            title: "Pie Chart",
            messageId: "sidebar.recharts.pieChart",
            url: "/third-party/recharts/pie",
          },
          {
            id: "radar",
            title: "Radar Chart",
            messageId: "sidebar.recharts.radarChart",
            url: "/third-party/recharts/radar",
          },
          {
            id: "radial",
            title: "Radial Chart",
            messageId: "sidebar.recharts.radialChart",
            url: "/third-party/recharts/radial",
          },
          {
            id: "scatter",
            title: "Scatter Chart",
            messageId: "sidebar.recharts.scatterChart",
            url: "/third-party/recharts/scatter",
          },
          {
            id: "funnel",
            title: "Funnel Chart",
            messageId: "sidebar.recharts.funnelChart",
            url: "/third-party/recharts/funnel",
          },
          {
            id: "treemap",
            title: "Treemap Chart",
            messageId: "sidebar.recharts.treeChart",
            url: "/third-party/recharts/treemap",
          },
        ],
      },
      {
        id: "filestack",
        title: "Filestack",
        messageId: "sidebar.filestack",

        icon: <RiFileUploadLine />,
        url: "/third-party/filestack",
      },
      {
        id: "froala-editor",
        title: "Froala Editor",
        messageId: "sidebar.froalaEditor",

        icon: <AiOutlineEdit />,
        url: "/third-party/froala-editor",
      },
      {
        id: "fusion-charts",
        title: "Fusion Charts",
        messageId: "sidebar.fusionCharts",

        icon: <RiBarChart2Line />,
        url: "/third-party/fusion-charts",
      },
      {
        id: "big-calendar",
        title: "Big Calendar",
        messageId: "sidebar.bigCalender",
        icon: <FaRegCalendarAlt />,
        url: "/third-party/calendar",
      },
      {
        id: "slick",
        title: "React Slick",
        messageId: "sidebar.reactSlick",
        icon: <BiCarousel />,

        url: "/third-party/slider",
      },
      {
        id: "react-color",
        title: "React Color",
        messageId: "sidebar.reactColor",
        icon: <MdInvertColors />,
        url: "/third-party/react-color",
      },
      {
        id: "react-dropzone",
        title: "React Dropzone",
        messageId: "sidebar.reactDropzone",
        icon: <CgAttachment />,
        url: "/third-party/react-dropzone",
      },
      {
        id: "react-notification",
        title: "React Notification",
        messageId: "sidebar.reactNotification",
        icon: <IoMdNotificationsOutline />,
        url: "/third-party/react-notification",
      },

      {
        id: "react-player",
        title: "Player",
        messageId: "sidebar.player",
        icon: <DiHtml5Multimedia />,
        url: "/third-party/react-player",
      },
      {
        id: "time-line",
        title: "Time Line",
        messageId: "sidebar.pages.timeLine",
        icon: <MdTimeline />,
        url: "/third-party/time-line",
      },
    ],
  },
  {
    id: "components",
    title: "Components",
    messageId: "sidebar.components",
    type: "group",
    children: [
      {
        id: "general",
        title: "General",
        messageId: "sidebar.components.general",
        icon: <TiMap />,
        url: "general",
        type: "collapse",
        children: [
          {
            id: "button",
            title: "Button",
            messageId: "sidebar.general.button",
            url: "/components/general/button",
          },
          {
            id: "typography",
            title: "Typography",
            messageId: "sidebar.general.typography",
            url: "/components/general/typography",
          },
          {
            id: "icon",
            title: "Icon",
            messageId: "sidebar.general.icon",
            url: "/components/general/icon",
          },
        ],
      },
      {
        id: "navigation",
        title: "Navigation",
        messageId: "sidebar.components.navigation",
        icon: <RiEqualizerLine />,
        url: "navigation",
        type: "collapse",
        children: [
          {
            id: "affix",
            title: "Affix",
            messageId: "sidebar.navigation.affix",
            url: "/components/navigation/affix",
          },
          {
            id: "breadcrumb",
            title: "Breadcrumb",
            messageId: "sidebar.navigation.breadcrumb",
            url: "/components/navigation/breadcrumb",
          },
          {
            id: "dropdown",
            title: "Dropdown",
            messageId: "sidebar.navigation.dropdown",
            url: "/components/navigation/dropdown",
          },
          {
            id: "menu",
            title: "Menu",
            messageId: "sidebar.navigation.menu",
            url: "/components/navigation/menu",
          },
          {
            id: "page-header",
            title: "PageHeader",
            messageId: "sidebar.navigation.pageHeader",
            url: "/components/navigation/page-header",
          },
          {
            id: "pagination",
            title: "Pagination",
            messageId: "sidebar.navigation.pagination",
            url: "/components/navigation/pagination",
          },
          {
            id: "steps",
            title: "Steps",
            messageId: "sidebar.navigation.steps",
            url: "/components/navigation/steps",
          },
        ],
      },
      {
        id: "dataEntry",
        title: "Data Entry",
        messageId: "sidebar.components.dataEntry",
        icon: <AiOutlineDatabase />,
        url: "dataEntry",
        type: "collapse",
        children: [
          {
            id: "auto-complete",
            title: "AutoComplete",
            messageId: "sidebar.dataEntry.autoComplete",
            url: "/components/dataEntry/auto-complete",
          },
          {
            id: "checkbox",
            title: "Checkbox",
            messageId: "sidebar.dataEntry.checkbox",
            url: "/components/dataEntry/checkbox",
          },
          {
            id: "cascader",
            title: "Cascader",
            messageId: "sidebar.dataEntry.cascader",
            url: "/components/dataEntry/cascader",
          },
          {
            id: "date-picker",
            title: "Datepicker",
            messageId: "sidebar.dataEntry.datePicker",
            url: "/components/dataEntry/date-picker",
          },
          {
            id: "form",
            title: "Form",
            messageId: "sidebar.dataEntry.form",
            url: "/components/dataEntry/form",
          },
          {
            id: "inputNumber",
            title: "InputNumber",
            messageId: "sidebar.dataEntry.inputNumber",
            url: "/components/dataEntry/inputNumber",
          },
          {
            id: "input",
            title: "Input",
            messageId: "sidebar.dataEntry.input",
            url: "/components/dataEntry/input",
          },
          {
            id: "mention",
            title: "Mention",
            messageId: "sidebar.dataEntry.mention",
            url: "/components/dataEntry/mention",
          },
          {
            id: "rate",
            title: "Rate",
            messageId: "sidebar.dataEntry.rate",
            url: "/components/dataEntry/rate",
          },
          {
            id: "radio",
            title: "Radio",
            messageId: "sidebar.dataEntry.radio",
            url: "/components/dataEntry/radio",
          },
          {
            id: "switch",
            title: "Switch",
            messageId: "sidebar.dataEntry.switch",
            url: "/components/dataEntry/switch",
          },
          {
            id: "slider",
            title: "Slider",
            messageId: "sidebar.dataEntry.slider",
            url: "/components/dataEntry/slider",
          },
          {
            id: "select",
            title: "Select",
            messageId: "sidebar.dataEntry.select",
            url: "/components/dataEntry/select",
          },
          {
            id: "tree-select",
            title: "TreeSelect",
            messageId: "sidebar.dataEntry.treeSelect",
            url: "/components/dataEntry/tree-select",
          },
          {
            id: "transfer",
            title: "Transfer",
            messageId: "sidebar.dataEntry.transfer",
            url: "/components/dataEntry/transfer",
          },
          {
            id: "time-picker",
            title: "Time Picker",
            messageId: "sidebar.dataEntry.timePicker",
            url: "/components/dataEntry/time-picker",
          },
          {
            id: "upload",
            title: "Upload",
            messageId: "sidebar.dataEntry.upload",
            url: "/components/dataEntry/upload",
          },
        ],
      },
      {
        id: "dataDisplay",
        title: "Data Display",
        messageId: "sidebar.components.dataDisplay",
        icon: <BiData />,
        url: "dataDisplay",
        type: "collapse",
        children: [
          {
            id: "avatar",
            title: "Avatar",
            messageId: "sidebar.dataDisplay.avatar",
            url: "/components/dataDisplay/avatar",
          },
          {
            id: "badge",
            title: "Badge",
            messageId: "sidebar.dataDisplay.badge",
            url: "/components/dataDisplay/badge",
          },
          {
            id: "collapse",
            title: "Collapse",
            messageId: "sidebar.dataDisplay.collapse",
            url: "/components/dataDisplay/collapse",
          },
          {
            id: "carousel",
            title: "Carousel",
            messageId: "sidebar.dataDisplay.carousel",
            url: "/components/dataDisplay/carousel",
          },
          {
            id: "card",
            title: "Card",
            messageId: "sidebar.dataDisplay.card",
            url: "/components/dataDisplay/card",
          },
          {
            id: "calendar",
            title: "Calendar",
            messageId: "sidebar.dataDisplay.calender",
            url: "/components/dataDisplay/calendar",
          },
          {
            id: "list",
            title: "List",
            messageId: "sidebar.dataDisplay.list",
            url: "/components/dataDisplay/list",
          },
          {
            id: "popover",
            title: "Popover",
            messageId: "sidebar.dataDisplay.popover",
            url: "/components/dataDisplay/popover",
          },
          {
            id: "tree",
            title: "Tree",
            messageId: "sidebar.dataDisplay.tree",
            url: "/components/dataDisplay/tree",
          },
          {
            id: "tooltip",
            title: "Tooltips",
            messageId: "sidebar.dataDisplay.toolTips",
            url: "/components/dataDisplay/tooltip",
          },
          {
            id: "timeline",
            title: "Timeline",
            messageId: "sidebar.dataDisplay.timeLine",
            url: "/components/dataDisplay/timeline",
          },
          {
            id: "tag",
            title: "Tag",
            messageId: "sidebar.dataDisplay.tag",
            url: "/components/dataDisplay/tag",
          },
          {
            id: "tabs",
            title: "Tabs",
            messageId: "sidebar.dataDisplay.tabs",
            url: "/components/dataDisplay/tabs",
          },
          {
            id: "comment",
            title: "Comment",
            messageId: "sidebar.dataDisplay.comment",
            url: "/components/dataDisplay/comment",
          },
          {
            id: "descriptions",
            title: "Descriptions",
            messageId: "sidebar.dataDisplay.descriptions",
            url: "/components/dataDisplay/descriptions",
          },
          {
            id: "empty",
            title: "Empty",
            messageId: "sidebar.dataDisplay.empty",
            url: "/components/dataDisplay/empty",
          },
          {
            id: "image",
            title: "Image",
            messageId: "sidebar.dataDisplay.image",
            url: "/components/dataDisplay/image",
          },
          {
            id: "statistic",
            title: "Statistic",
            messageId: "sidebar.dataDisplay.statistic",
            url: "/components/dataDisplay/statistic",
          },
        ],
      },

      {
        id: "feedBack",
        title: "FeedBack",
        messageId: "sidebar.components.feedBack",
        icon: <VscFeedback />,
        url: "feedBack",
        type: "collapse",
        children: [
          {
            id: "alert",
            title: "Alert",
            messageId: "sidebar.feedBack.alert",
            url: "/components/feedBack/alert",
          },
          {
            id: "modal",
            title: "Modal",
            messageId: "sidebar.feedBack.modal",
            url: "/components/feedBack/modal",
          },
          {
            id: "message",
            title: "Message",
            messageId: "sidebar.feedBack.message",
            url: "/components/feedBack/message",
          },
          {
            id: "notification",
            title: "Notification",
            messageId: "sidebar.feedBack.notification",
            url: "/components/feedBack/notification",
          },
          {
            id: "progress",
            title: "Progress",
            messageId: "sidebar.feedBack.progress",
            url: "/components/feedBack/progress",
          },
          {
            id: "pop-confirm",
            title: "PopConfirm",
            messageId: "sidebar.feedBack.popConfirm",
            url: "/components/feedBack/pop-confirm",
          },
          {
            id: "spin",
            title: "Spin",
            messageId: "sidebar.feedBack.spin",
            url: "/components/feedBack/spin",
          },
          {
            id: "drawer",
            title: "Drawer",
            messageId: "sidebar.feedBack.drawer",
            url: "/components/feedBack/drawer",
          },
          {
            id: "result",
            title: "Result",
            messageId: "sidebar.feedBack.result",
            url: "/components/feedBack/result",
          },
          {
            id: "skeleton",
            title: "Skeleton",
            messageId: "sidebar.feedBack.skeleton",
            url: "/components/feedBack/skeleton",
          },
        ],
      },
      {
        id: "other",
        title: "Other",
        messageId: "sidebar.components.other",
        icon: <MdDevicesOther />,
        url: "other",
        type: "collapse",
        children: [
          {
            id: "anchor",
            title: "Anchor",
            messageId: "sidebar.other.anchor",
            url: "/components/other/anchor",
          },
          {
            id: "backTop",
            title: "BackTop",
            messageId: "sidebar.other.backTop",
            url: "/components/other/backTop",
          },
          {
            id: "divider",
            title: "Divider",
            messageId: "sidebar.other.divider",
            url: "/components/other/divider",
          },
          {
            id: "config-provider",
            title: "ConfigProvider",
            messageId: "sidebar.other.configProvider",
            url: "/components/other/config-provider",
          },
        ],
      },
      {
        id: "layout",
        title: "Layout",
        messageId: "sidebar.components.layout",
        icon: <AiOutlineLayout />,
        url: "layout",
        type: "collapse",
        children: [
          {
            id: "layout-divider",
            title: "Divider",
            messageId: "sidebar.layout.divider",
            url: "/components/layout/divider",
          },
          {
            id: "space",
            title: "Space",
            messageId: "sidebar.layout.space",
            url: "/components/layout/space",
          },
        ],
      },
      {
        id: "table",
        title: "Table",
        messageId: "sidebar.dataDisplay.table",
        icon: <BsTable />,
        url: "table",
        type: "collapse",
        children: [
          {
            id: "basic-table",
            title: "Basic",
            messageId: "sidebar.bigCalender.basic",
            url: "/components/table/basic-table",
          },
        ],
      },
    ],
  },
  {
    id: "extra-pages",
    title: "Extra Pages",
    messageId: "sidebar.pages.extraPages",
    url: "extra-pages",
    type: "group",
    children: [
      {
        id: "account",
        title: "Account",
        messageId: "sidebar.pages.extraPages.account",
        icon: <MdOutlineManageAccounts />,
        url: "/extra-pages/account",
      },
      {
        id: "about-us",
        title: "About Us",
        messageId: "sidebar.pages.extraPages.aboutUs",
        icon: <FiUsers />,
        url: "/extra-pages/about-us",
      },
      {
        id: "contact-us",
        title: "Contact Us",
        messageId: "sidebar.pages.extraPages.contactUs",
        icon: <MdOutlineContactSupport />,
        url: "/extra-pages/contact-us",
      },
      {
        id: "knowledge-base",
        title: "Knowledge Base",
        messageId: "sidebar.pages.extraPages.knowledgeBase",
        icon: <BiBookReader />,
        url: "/extra-pages/knowledge-base",
      },
      {
        id: "portfolio",
        title: "Portfolio",
        messageId: "sidebar.pages.extraPages.portfolio",
        icon: <BsBriefcase />,
        url: "/extra-pages/portfolio",
      },
      {
        id: "faq",
        title: "FAQ",
        messageId: "sidebar.pages.extraPages.faq",
        icon: <BsQuestionDiamond />,
        url: "/extra-pages/faq",
      },
      {
        id: "pricing",
        title: "Pricing",
        messageId: "sidebar.pages.extraPages.pricing",
        icon: <BiDollar />,
        url: "pricing",
        type: "collapse",
        children: [
          {
            id: "pricingListing",
            title: "Pricing Listing",
            messageId: "sidebar.pages.extraPages.pricingListing",
            url: "/extra-pages/pricing-listing",
          },
          {
            id: "pricingDetail",
            title: "Pricing Detail",
            messageId: "sidebar.pages.extraPages.pricingDetail",
            url: "/extra-pages/pricing-detail",
          },
        ],
      },
      {
        id: "user",
        title: "user Pages",
        messageId: "sidebar.pages.userPages",
        icon: <RiShieldUserLine />,
        url: "user",
        type: "collapse",
        children: [
          {
            id: "sign-in-1",
            title: "SignIn-1",
            messageId: "sidebar.pages.userPages.signIn1",
            url: "/extra-pages/user/sign-in-1",
          },
          {
            id: "sign-in-2",
            title: "SignIn-2",
            messageId: "sidebar.pages.userPages.signIn2",
            url: "/extra-pages/user/sign-in-2",
          },
          {
            id: "sign-up-1",
            title: "SignUp-1",
            messageId: "sidebar.pages.userPages.signUp1",
            url: "/extra-pages/user/sign-up-1",
          },
          {
            id: "sign-up-2",
            title: "SignUp-2",
            messageId: "sidebar.pages.userPages.signUp2",
            url: "/extra-pages/user/sign-up-2",
          },
          {
            id: "forgot-password-1",
            title: "Forgot Password-1",
            messageId: "sidebar.pages.userPages.forgetPassword1",
            url: "/extra-pages/user/forgot-password-1",
          },
          {
            id: "forgot-password-2",
            title: "Forgot Password-2",
            messageId: "sidebar.pages.userPages.forgetPassword2",
            url: "/extra-pages/user/forgot-password-2",
          },
          {
            id: "reset-password-1",
            title: "Reset Password-1",
            messageId: "sidebar.pages.userPages.resetPassword1",
            url: "/extra-pages/user/reset-password-1",
          },
          {
            id: "reset-password-2",
            title: "Reset Password-2",
            messageId: "sidebar.pages.userPages.resetPassword2",
            url: "/extra-pages/user/reset-password-2",
          },
          {
            id: "lock-1",
            title: "Lock Screen-1",
            messageId: "sidebar.pages.userPages.lockScreen1",
            url: "/extra-pages/user/lock-1",
          },
          {
            id: "lock-2",
            title: "Lock Screen-2",
            messageId: "sidebar.pages.userPages.lockScreen2",
            url: "/extra-pages/user/lock-2",
          },
        ],
      },
      {
        id: "list-type",
        title: "user List",
        messageId: "sidebar.pages.userList",
        icon: <CgUserList />,
        url: "list-type",
        type: "collapse",
        children: [
          {
            id: "morden",
            title: "Modern",
            messageId: "sidebar.pages.userList.modern",
            url: "/extra-pages/list-type/modern",
          },
          {
            id: "standard",
            title: "Standard",
            messageId: "sidebar.pages.userList.standard",
            url: "/extra-pages/list-type/standard",
          },
          {
            id: "flat",
            title: "Flat",
            messageId: "sidebar.pages.userList.flat",
            url: "/extra-pages/list-type/flat",
          },
        ],
      },
      {
        id: "error-pages",
        title: "Error Pages",
        messageId: "sidebar.pages.errorPages",
        icon: <BiErrorCircle />,
        url: "error-pages",
        type: "collapse",
        children: [
          {
            id: "error-401",
            title: "401",
            messageId: "sidebar.pages.errorPages.401",
            url: "/error-pages/error-401",
          },
          {
            id: "error-403",
            title: "403",
            messageId: "sidebar.pages.errorPages.403",
            url: "/error-pages/error-403",
          },
          {
            id: "error-404",
            title: "404",
            messageId: "sidebar.pages.errorPages.404",
            url: "/error-pages/error-404",
          },
          {
            id: "error-500",
            title: "500",
            messageId: "sidebar.pages.errorPages.500",
            url: "/error-pages/error-500",
          },
          {
            id: "maintenance",
            title: "Maintenance",
            messageId: "sidebar.pages.errorPages.maintenance",
            url: "/error-pages/maintenance",
          },
          {
            id: "coming-soon",
            title: "Coming Soon",
            messageId: "sidebar.pages.errorPages.comingSoon",
            url: "/error-pages/coming-soon",
          },
        ],
      },
    ],
  },
];
export default routesConfig;
